name: Run Gradle on PRs
on: pull_request
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: ./installDependencies.sh
    - run: ./buildAll.sh
    - run: xvfb-run -a yarn test
      if: runner.os == 'Linux'
    - run: yarn test
      if: runner.os != 'Linux'
